name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Update the config
      run: echo "export const setings = {host:\"https://localhost:3030\"}" > src/config.js
    - name: Start Backend
      run: npm run server &
    - name: Start Frontend
      run: npm run start &
    - name: Install Playwright Browsers
      run: npx playwright install                                              
    - name: Run tests
      run: npm run test
